release = ""
project = "python-build-standalone"
copyright = "2020, Gregory Szorc"
author = "Gregory Szorc"
extensions = []
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "alabaster"
html_static_path = ["_static"]
master_doc = "index"
